In [13]:
from utils import *

import numpy as np
import pymap3d as pm
from Timer import Timer

In [1]:
import os   

import sys

os.path.dirname(os.path.abspath(__file__))

NameError: name '__file__' is not defined

In [3]:
lla0 = [41.102275061226244, 29.0245487284028, 0]

lla1 = [41.111279536740533	,29.036452782236729	,-1000]

ned = lla2ned(lla1[0], lla1[1], lla1[2], lla0[0], lla0[1], lla0[2])

In [14]:
ned2 = pm.geodetic2ned(lla1[0], lla1[1], lla1[2], lla0[0], lla0[1], lla0[2])

In [4]:
ned

(1002.3736291113255, 998.5523583937108, 1000)

In [51]:

with Timer("NED to ENU conversion"):
    for i in range(10):

        ned2 = pm.geodetic2ned(lla1[0], lla1[1], lla1[2], lla0[0], lla0[1], lla0[2])
        # ned = lla2ned(lla1[0], lla1[1], lla1[2], lla0[0], lla0[1], lla0[2])

[NED to ENU conversion]
Elapsed: 0.00586700439453125


In [ ]:

R = quat2rotm(eul2quat(np.deg2rad([45, 0, 0])))  


In [11]:
R  @ np.array([[1, 0, 0]]).T  # Rotate the vector [1, 0, 0] by the rotation matrix R

array([[0.70710678],
       [0.70710678],
       [0.        ]])

In [ ]:
np.array([1, 0, 0]).T.

(3,)

In [44]:

mag = np.array([100, 56, 0])  # Example magnetometer reading
quat = eul2quat(np.deg2rad([0, -30, 0]))  # Example quaternion from MAVROS
quat_mavros = quat[1], quat[2], quat[3], quat[0]  # Reorder to [w, x, y, z]
heading = calculate_heading(mag, quat_mavros, 0)
print(f"Heading: {np.rad2deg(heading)} degrees")


Heading: 32.888013823689334 degrees


In [3]:
quat_mavros

(0.0, 0.0, 0.0, 1.0)

In [15]:
heading

0.8068730671576461

In [59]:
np.random.seed(0)
R = np.random.rand(3, 3)
R_tile = np.tile(R, (4, 1, 1))

print(R)


print(R_tile.shape)

v = np.random.rand(3)
print(v)
print(v.shape)

print((R_tile.dot(v)))

print((5*(R_tile @ v)))



[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
(4, 3, 3)
[0.38344152 0.79172504 0.52889492]
(3,)
[[1.0954697  0.88595906 1.38350446]
 [1.0954697  0.88595906 1.38350446]
 [1.0954697  0.88595906 1.38350446]
 [1.0954697  0.88595906 1.38350446]]
[[5.4773485  4.42979531 6.91752228]
 [5.4773485  4.42979531 6.91752228]
 [5.4773485  4.42979531 6.91752228]
 [5.4773485  4.42979531 6.91752228]]


In [ ]:
from scipy.stats import norm

norm.ppf(0.6)

np.float64(0.2533471031357997)

In [259]:
1746433619173440000 + (0.1)*1e9

1.74643361927344e+18

In [87]:
arr = np.arange(10)


# arr = np.random.shuffle(arr)
# print(arr)

a = np.random.shuffle(arr)
print(a)


None


In [9]:
from utils import *

wrap2_pi(np.random.rand(1,10))

array([[ 0.69355581,  2.5811645 ,  2.34115902,  0.61717768,  3.08772877,
         1.37051904,  1.70509866,  2.21379594, -2.77592676,  0.99302111]])

In [257]:
1 / (1403636579813550000 - 1403636579863550000) * 1e9

-20.0

In [245]:
fold = 'data/videos/itu_video_05052025.npy'
dt = np.load(fold)
import cv2

In [250]:
dt[1200].shape

(256, 256, 3)

In [255]:
cv2.imshow('a',cv2.resize(dt[1200], (600,600)))
cv2.waitKey(0)
cv2.destroyAllWindows()


In [69]:
alt                     = 100
rotM_hypo               = quat2rotm(eul2quat(np.deg2rad([0,45,-30])))                           # shape (N, 3, 3)
range_fimder_body       = np.array([0, 0, 1])                       # Assuming the range is in the Z direction
range_finder_world      = rotM_hypo @ range_fimder_body             # shape (N, 3)
scale                   = abs(alt) / range_finder_world[2]  # shape (N,)
delta_pos               = range_finder_world * scale.reshape(-1,1)  # shape (N, 3)
print(delta_pos)

[[100.          81.64965809 100.        ]]


In [54]:
m = arr.shape[0]

with Timer('a'):
    
    for i in range(50000):

        drop_idx = np.random.choice(m, size=n, replace=False)  # O(n)
        new_arr  = np.delete(arr, drop_idx, axis=0)            # O((m-n)*k)

[a]
Elapsed: 0.48070287704467773


In [14]:
new_arr

array([ 1,  6,  8, 10, 13, 15, 17, 18, 19, 20, 22, 24, 26, 27, 30, 31, 32,
       34, 36, 38, 44, 49, 50, 51, 52, 53, 55, 57, 59, 60, 62, 63, 65, 66,
       67, 70, 72, 80, 81, 82, 83, 84, 86, 87, 88, 90, 92, 93, 96, 98])