In [82]:
import numpy as np

arr = np.arange(100)
n = 20  # number of rows to remove
m = arr.shape[0]

# np.random.seed(0)

# with Timer('a'):
    
#     for i in range(50000):

#         perm = np.random.permutation(m)    # O(m)
#         keep_idx = perm[n:]               # indices of rows to keep
#         new_arr = arr[keep_idx]            # O((m-n)*k)
        
# new_arr.shape
# keep_idx.shape
arr[2:5]


array([2, 3, 4])

In [19]:
from utils import *
import numpy as np
# Generate a random quaternion
quat = np.array([0.7071, 0.0, 0.7071, 0.0])  # Example quaternion (w, x, y, z)
quat = np.tile(quat, (4, 1))

rotm = quat2rotm(quat)
a = quat2eul(rotm2quat(rotm))

a.shape

c:\Users\cyber\anaconda3\envs\bakiMPF\Lib\site-packages\IPython\core\interactiveshell.py:3579: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  exec(code_obj, self.user_global_ns, self.user_ns)


(4, 3)

In [59]:
np.random.seed(0)
R = np.random.rand(3, 3)
R_tile = np.tile(R, (4, 1, 1))

print(R)


print(R_tile.shape)

v = np.random.rand(3)
print(v)
print(v.shape)

print((R_tile.dot(v)))

print((5*(R_tile @ v)))



[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
(4, 3, 3)
[0.38344152 0.79172504 0.52889492]
(3,)
[[1.0954697  0.88595906 1.38350446]
 [1.0954697  0.88595906 1.38350446]
 [1.0954697  0.88595906 1.38350446]
 [1.0954697  0.88595906 1.38350446]]
[[5.4773485  4.42979531 6.91752228]
 [5.4773485  4.42979531 6.91752228]
 [5.4773485  4.42979531 6.91752228]
 [5.4773485  4.42979531 6.91752228]]


In [62]:
a = R_tile.dot(v)
a[:, 1] = 0
a

array([[1.0954697 , 0.        , 1.38350446],
       [1.0954697 , 0.        , 1.38350446],
       [1.0954697 , 0.        , 1.38350446],
       [1.0954697 , 0.        , 1.38350446]])

In [15]:
from Timer import Timer

In [69]:
alt                     = 100
rotM_hypo               = quat2rotm(eul2quat(np.deg2rad([0,45,-30])))                           # shape (N, 3, 3)
range_fimder_body       = np.array([0, 0, 1])                       # Assuming the range is in the Z direction
range_finder_world      = rotM_hypo @ range_fimder_body             # shape (N, 3)
scale                   = abs(alt) / range_finder_world[2]  # shape (N,)
delta_pos               = range_finder_world * scale.reshape(-1,1)  # shape (N, 3)
print(delta_pos)

[[100.          81.64965809 100.        ]]


In [54]:
m = arr.shape[0]

with Timer('a'):
    
    for i in range(50000):

        drop_idx = np.random.choice(m, size=n, replace=False)  # O(n)
        new_arr  = np.delete(arr, drop_idx, axis=0)            # O((m-n)*k)

[a]
Elapsed: 0.48070287704467773


In [14]:
new_arr

array([ 1,  6,  8, 10, 13, 15, 17, 18, 19, 20, 22, 24, 26, 27, 30, 31, 32,
       34, 36, 38, 44, 49, 50, 51, 52, 53, 55, 57, 59, 60, 62, 63, 65, 66,
       67, 70, 72, 80, 81, 82, 83, 84, 86, 87, 88, 90, 92, 93, 96, 98])