In [82]:
import numpy as np

arr = np.arange(100)
n = 20  # number of rows to remove
m = arr.shape[0]

# np.random.seed(0)

# with Timer('a'):
    
#     for i in range(50000):

#         perm = np.random.permutation(m)    # O(m)
#         keep_idx = perm[n:]               # indices of rows to keep
#         new_arr = arr[keep_idx]            # O((m-n)*k)
        
# new_arr.shape
# keep_idx.shape
arr[2:5]


array([2, 3, 4])

In [68]:
perm


array([29, 58, 66, 75, 27,  4, 41, 50, 63,  6, 74, 93, 15, 95, 46, 96,  3,
       78, 49, 91, 62, 20, 76, 48, 37,  7, 10, 70, 32, 98, 80, 68, 26, 94,
       81, 89, 59, 39, 18, 55, 67,  0,  9, 35, 17, 28, 73, 53, 69, 86,  2,
       47, 61, 87, 88, 45, 85,  1, 38, 84, 19, 83, 21, 52, 25, 44, 12, 64,
        5, 56, 99, 92, 24, 60, 97, 11, 36, 72, 23, 43, 90, 30, 40, 22, 33,
       31, 71, 77, 54, 42, 51, 13, 65, 16,  8, 34, 82, 57, 79, 14],
      dtype=int32)

In [69]:
perm[n:]

array([ 2, 47, 61, 87, 88, 45, 85,  1, 38, 84, 19, 83, 21, 52, 25, 44, 12,
       64,  5, 56, 99, 92, 24, 60, 97, 11, 36, 72, 23, 43, 90, 30, 40, 22,
       33, 31, 71, 77, 54, 42, 51, 13, 65, 16,  8, 34, 82, 57, 79, 14],
      dtype=int32)

In [15]:
from Timer import Timer

In [12]:
new_arr

array([96, 63, 52, 22, 31, 98, 14, 64, 70, 25, 12, 47, 58, 11, 68, 56, 79,
       28, 37,  7, 77, 39, 35,  4, 76, 65, 94, 32, 46, 30, 19, 95, 83, 43,
        1, 13, 55, 21, 57, 88, 18, 15, 34, 93, 74, 48, 27, 53, 36, 66])

In [54]:
m = arr.shape[0]

with Timer('a'):
    
    for i in range(50000):

        drop_idx = np.random.choice(m, size=n, replace=False)  # O(n)
        new_arr  = np.delete(arr, drop_idx, axis=0)            # O((m-n)*k)

[a]
Elapsed: 0.48070287704467773


In [14]:
new_arr

array([ 1,  6,  8, 10, 13, 15, 17, 18, 19, 20, 22, 24, 26, 27, 30, 31, 32,
       34, 36, 38, 44, 49, 50, 51, 52, 53, 55, 57, 59, 60, 62, 63, 65, 66,
       67, 70, 72, 80, 81, 82, 83, 84, 86, 87, 88, 90, 92, 93, 96, 98])