In [1]:
from utils_OV.guidance_utils import TrajectoryGeneratorV2
import numpy as np

In [5]:
from collections import deque
import numpy as np

In [5]:
all(np.array([1,2.1,3]) ==  np.array([1,2,3]))

False

In [3]:
(-0.058459263974390725, 0.11081390923091944, 0.3523873028224487) == (-0.05845926397439025, 0.11081390923091944, 0.3523873028224487)



False

In [14]:
IMU_acc_buf.append(np.array([0.1, 0.2, 0.3]))

In [18]:
np.array(IMU_acc_buf) - IMU_acc_buf

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
with open('config/guidance_and_control_parameters.yaml') as f:
    gc_params = yaml.safe_load(f)

In [18]:
traj = TrajectoryGeneratorV2(sampling_freq=10, max_vel=[8.0,8,8], max_acc=[5.0,5,5])

wpts_alt = 30.0
edge_length = 50.0
# Generate waypoints
wp_list = traj.generate_wp_list_for_square_trajectory(edge_length, wpts_alt)
# wp_list = np.vstack((wp_list, wp_list, wp_list))

In [19]:
wp_list = np.array(wp_list)
#initial_position = np.array([0,0,0.0])


In [16]:
shaped_wp_list = np.insert(wp_list, 3, initial_position, axis=0)


In [17]:
shaped_wp_list

array([[  0.,   0., -30.],
       [ 25.,   0., -30.],
       [ 50.,   0., -30.],
       [  0.,   0.,   0.],
       [ 50., -25., -30.],
       [ 50., -50., -30.],
       [ 25., -50., -30.],
       [  0., -50., -30.],
       [  0., -25., -30.],
       [  0.,   0., -30.]])

In [20]:
traj.generate_traj_from_wplist_interp(wp_list, coordinate_type="ned")
generated_traj = traj.get_pos_vel_acc_in_ned()


In [32]:
generated_traj['pos']

array([[ 0.00000000e+00,  0.00000000e+00, -3.00000000e+01],
       [ 1.16518990e-02, -5.01743018e-06, -3.00000000e+01],
       [ 4.61049353e-02, -4.01394415e-05, -3.00000000e+01],
       ...,
       [ 1.35470615e-04, -1.02605118e-01, -3.00000000e+01],
       [ 4.01394415e-05, -4.61049353e-02, -3.00000000e+01],
       [ 5.01743018e-06, -1.16518990e-02, -3.00000000e+01]])

In [33]:
traj.generate_traj_from_wplist_interp(np.array([np.array([1,2,3]), np.array([0,0,0]) ]), coordinate_type="ned")
generated_traj = traj.get_pos_vel_acc_in_ned()

In [37]:
generated_traj['pos']

array([[ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00],
       [ 9.87301587e-01,  1.98738624e+00,  2.97468783e+00],
       [ 9.51746032e-01,  1.95242328e+00,  2.90416931e+00],
       [ 8.97142857e-01,  1.89942857e+00,  2.79657143e+00],
       [ 8.27301587e-01,  1.83271958e+00,  2.66002116e+00],
       [ 7.46031746e-01,  1.75661376e+00,  2.50264550e+00],
       [ 6.57142857e-01,  1.67542857e+00,  2.33257143e+00],
       [ 5.64444444e-01,  1.59348148e+00,  2.15792593e+00],
       [ 4.71700176e-01,  1.51497707e+00,  1.98667725e+00],
       [ 3.81619048e-01,  1.44152381e+00,  1.82314286e+00],
       [ 2.95855379e-01,  1.37213404e+00,  1.66798942e+00],
       [ 2.16017637e-01,  1.30570723e+00,  1.52172487e+00],
       [ 1.43714286e-01,  1.24114286e+00,  1.38485714e+00],
       [ 8.05537919e-02,  1.17734039e+00,  1.25789418e+00],
       [ 2.81446208e-02,  1.11319929e+00,  1.14134392e+00],
       [-1.19047619e-02,  1.04761905e+00,  1.03571429e+00],
       [-3.86208113e-02,  9.79668430e-01

In [6]:
traj = TrajectoryGeneratorV2(sampling_freq=10, max_vel=[8.0,8,8], max_acc=[5.0,5,5])

wp_list = traj.generate_wp_list_for_square_trajectory(100, 30, edge_inter_cp = 10)

11


In [20]:
wp_list = traj.generate_wp_list_for_square_trajectory(100, 30, edge_inter_cp = 3)

In [7]:
wp_list

[[0, 0, -30],
 [0.0, 0, -30],
 [9.090909090909092, 0, -30],
 [18.181818181818183, 0, -30],
 [27.272727272727273, 0, -30],
 [36.36363636363637, 0, -30],
 [45.45454545454546, 0, -30],
 [54.54545454545455, 0, -30],
 [63.63636363636364, 0, -30],
 [72.72727272727273, 0, -30],
 [81.81818181818183, 0, -30],
 [90.90909090909092, 0, -30],
 [100, 0.0, -30],
 [100, -9.090909090909092, -30],
 [100, -18.181818181818183, -30],
 [100, -27.272727272727273, -30],
 [100, -36.36363636363637, -30],
 [100, -45.45454545454546, -30],
 [100, -54.54545454545455, -30],
 [100, -63.63636363636364, -30],
 [100, -72.72727272727273, -30],
 [100, -81.81818181818183, -30],
 [100, -90.90909090909092, -30],
 [100.0, -100, -30],
 [90.9090909090909, -100, -30],
 [81.81818181818181, -100, -30],
 [72.72727272727272, -100, -30],
 [63.63636363636363, -100, -30],
 [54.54545454545454, -100, -30],
 [45.45454545454545, -100, -30],
 [36.36363636363636, -100, -30],
 [27.272727272727266, -100, -30],
 [18.181818181818173, -100, -30],

In [1]:
R_vioref2enu = quat2rotm(eul2quat([yaw_diff, 0, 0], order='ZYX'))   # vio to ENU


NameError: name 'quat2rotm' is not defined

In [3]:
!cd ..

In [6]:
from utils import quat2rotm, eul2quat, rotm2quat, quat2eul
import numpy as np


In [11]:
yaw_diff = np.deg2rad(-15)  # Example yaw difference in radians

R_inertia2body = quat2rotm(eul2quat([yaw_diff, 0, 0], order='ZYX'))   # vio to ENU

p_inertia = [1, 1, 3]

p_body = R_inertia2body @ np.array(p_inertia)
print('p_bod:', p_body)



p_bod: [1.22474487 0.70710678 3.        ]


In [12]:
yaw_diff_1 = np.deg2rad(30)  # Example yaw difference in radians
yaw_diff_2 = np.deg2rad(-45)  # Example yaw difference in radians


R_inertia2body_1 = quat2rotm(eul2quat([yaw_diff_1, 0, 0], order='ZYX'))   # vio to ENU
R_inertia2body_2 = quat2rotm(eul2quat([yaw_diff_2, 0, 0], order='ZYX'))   # vio to ENU

p_inertia = [1, 1, 3]

p_body = R_inertia2body_2  @ R_inertia2body_1 @ np.array(p_inertia)
print('p_bod:', p_body)

p_bod: [1.22474487 0.70710678 3.        ]


In [6]:
(0.004242640687119285  ** 2) *  (1/200) 

# a = 9e-8

# (a * 200) ** 0.5

8.999999999999999e-08